import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
   return (
      <Html>
         <Head>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
            <link
               href="https://fonts.googleapis.com/icon?family=Material+Icons"
               rel="stylesheet"
            ></link>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
               rel="preconnect"
               href="https://fonts.gstatic.com"
               crossOrigin="true"
            />
            <link
               href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap"
               rel="stylesheet"
            ></link>
         </Head>
         <body>
            <Main />
            <NextScript />
         </body>
      </Html>
   );
}
