import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import HomePage from "../components/HomePage";
import About from "../components/About";
import Sidebar from "../components/Sidebar";

const Home: NextPage = () => {
   return (
      <div className="flex flex-col">
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link
               href="https://fonts.googleapis.com/icon?family=Material+Icons"
               rel="stylesheet"
            ></link>
         </Head>
         <Navbar />
         <Sidebar />
         <HomePage />
         <About />
         <div></div>
      </div>
   );
};

export default Home;
